'use strict';
//setup variables
const gif = true;
const animation = false;
const fr = 1;
const capture = false;
const capture_time = 50/fr;

const suggested_palettes = [];

function gui_values(){
}

function setup() {
  common_setup();
  gui_values();
  noFill();
  rectMode(CENTER);

}
//***************************************************
function draw() {
  global_draw_start();
  push();
  
  refresh_working_palette();

  png_bg(true);
  const columns = ceil(random(8));
  const rows = ceil(random(8));

  //calculate the row and column sizes
  const column_size = width / columns;
  const row_size = height / rows;

  const rotation = Boolean(round(random()));
  const fixed_rot_amount = random([0, 1, 5])
  const oversized = Boolean(round(random()));
  const even_steps = Boolean(round(random()));
  const translation_offset = Boolean(round(random()));
  const filled = Boolean(random()>0.7);
  const round_corners = Boolean(round(random()));

  strokeWeight(random(0.5,3)*global_scale);

  //correct for offset generated by rectMode(CENTER)
  translate(column_size / 2, row_size / 2);

  //move through grid, top to bottom, left to right
  for (let i = 0; i < columns; i++) {   //loop through columns
    for (let j = 0; j < rows; j++) {    //loop through rows
      push(); // pair with pop
      //move origin to next grid tile
      translate(i * column_size, j * row_size);

      //generate random starting size for square
      let max_size = column_size;
      if (oversized) max_size = column_size * 2;

      let square_size = random(column_size * 0.25, max_size);

      while (square_size > 0) { //create concentric squares
        //assign random color to square outline
        const c = random(palette);
        if(filled) fill(c);
        stroke(c);

        if(translation_offset){
          //apply small random translation to square position
          const tx = random(-column_size * 0.1, column_size * 0.1);
          const ty = random(-row_size * 0.1, row_size * 0.1);
          translate(tx, ty);
        }

        //draw square
        if(rotation){
          if(fixed_rot_amount != 0) rotate(random(30));
          else rotate(fixed_rot_amount);
        }

        if(round_corners)square(0, 0, square_size, random([0, column_size * 0.2]), random([0, column_size * 0.2]), random([0, column_size * 0.2]), random([0, column_size * 0.2]));
        else square(0, 0, square_size);

        //reduce square size
        let decrement = random(column_size * 0.4);
        if(even_steps) decrement = column_size * 0.1;
        square_size -= decrement;
      }
      pop(); //revert origin back to original location
    }
  }
  

  pop();
  global_draw_end();
}
//***************************************************
//custom funcs